version: "3"

volumes:
  postgres-data:
    driver: local
  
services:
  db:
    image: "postgres:10"
    restart: always
    container_name: "my_postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    environment:
      POSTRES_USER: postgres
      POSTRES_PASSWORD: root